


export const ADD_CIRCLE = 'ADD_CIRCLE'
export const REMOVE_CIRCLE = 'REMOVE_CIRCLE'
export const SELECT_ROOT = 'SELECT_ROOT'
export const SELECT_MODE = 'SELECT_MODE'
export const SELECT_CHORD = 'SELECT_CHORD'
export const TOGGLE_CHROMATIC = 'TOGGLE_CHROMATIC'
export const UPDATE_NOTES = 'UPDATE_NOTES'